FROM python
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt

# runs the production server
CMD  ["python", "manage.py makemigrations"]
CMD ["python", "manage.py migrate"]
CMD ["python", "manage.py runserver"]