# Generated by Django 4.2.4 on 2023-09-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(default='')),
                ('dataSize', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
                ('timeSeries_type', models.CharField(choices=[('multiplicative', 'multiplicative'), ('additive', 'additive')], default='additive', max_length=25)),
                ('metaData', models.CharField(default=None, max_length=50)),
                ('producer_type', models.CharField(default=None, max_length=25)),
                ('process_id', models.IntegerField(default=None)),
                ('status', models.CharField(default='Added', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=5)),
                ('noiseLevel', models.CharField(max_length=15)),
                ('trendCoef', models.IntegerField(default=0)),
                ('missingPercent', models.IntegerField(default=0)),
                ('outlierPercent', models.IntegerField(default=0)),
                ('cycle_amplitude', models.IntegerField(choices=[('multiplicative', 1), ('additive', 0)])),
                ('cycle_frequency', models.CharField(max_length=25)),
                ('simulaterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulator')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.IntegerField(default=1)),
                ('phase_shift', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
                ('frequency_type', models.CharField(choices=[('Daily', 'Daily'), ('weekly', 'weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10)),
                ('frequency_multiplie', models.FloatField(default=0.0)),
                ('dataconfigID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.dataconfig')),
            ],
        ),
    ]
