# Generated by Django 4.2.4 on 2023-09-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(default='')),
                ('dataSize', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
                ('timeSeries_type', models.CharField(choices=[('multiplicative', 'multiplicative'), ('additive', 'additive')], default='additive', max_length=25)),
                ('metaData', models.CharField(default='', max_length=50)),
                ('producer_type', models.CharField(max_length=25)),
                ('process_id', models.IntegerField(null=True)),
                ('status', models.CharField(default='Added', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=5)),
                ('noiseLevel', models.IntegerField()),
                ('trendCoef', models.CharField(default='', max_length=15)),
                ('missingPercent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('outlierPercent', models.IntegerField(default=0)),
                ('cycle_amplitude', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('cycle_frequency', models.IntegerField()),
                ('simulaterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulator')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.IntegerField()),
                ('phase_shift', models.IntegerField()),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10)),
                ('multiplier', models.IntegerField(default=0)),
                ('dataconfigID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.dataconfig')),
            ],
        ),
    ]
