# Generated by Django 4.2.4 on 2023-09-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='dataconfigID',
            new_name='dataconfig',
        ),
        migrations.RenameField(
            model_name='dataconfig',
            old_name='simulaterID',
            new_name='simulater',
        ),
    ]
