# Generated by Django 4.2.4 on 2023-09-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0002_rename_dataconfigid_component_dataconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dataconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='simulator_api.dataconfig'),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='simulater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataConfig', to='simulator_api.simulator'),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='producer_type',
            field=models.CharField(choices=[('multiplicative', 'multiplicative'), ('additive', 'additive')], max_length=25),
        ),
    ]
