# Generated by Django 4.2.4 on 2023-09-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0003_alter_component_dataconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='simulater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='simulator_api.simulator'),
        ),
    ]
