# Generated by Django 4.2.4 on 2023-09-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0004_alter_simulator_enddate_alter_simulator_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='cycle_frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='missingPercent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='noiseLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='trendCoef',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='metaData',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='process_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='producer_type',
            field=models.CharField(max_length=25),
        ),
    ]
