# Generated by Django 4.2.4 on 2023-09-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0005_alter_dataconfig_cycle_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='cycle_amplitude',
            field=models.IntegerField(choices=[(1, 'multiplicative'), (0, 'additive')]),
        ),
    ]
