# Generated by Django 4.2.4 on 2023-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0006_alter_dataconfig_simulater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='metaData',
            field=models.CharField(default='', max_length=100),
        ),
    ]
