# Generated by Django 4.2.4 on 2023-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0006_alter_dataconfig_cycle_amplitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='cycle_amplitude',
            field=models.IntegerField(choices=[(1, 1), (0, 0)]),
        ),
    ]
