# Generated by Django 4.2.4 on 2023-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0007_alter_dataconfig_cycle_amplitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='frequency_type',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='component',
            name='frequency_multiplie',
        ),
        migrations.AddField(
            model_name='component',
            name='multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='amplitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='phase_shift',
            field=models.IntegerField(),
        ),
    ]
