# Generated by Django 4.2.4 on 2023-10-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0008_dataconfig_seasonality_components_simulator_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataconfig',
            name='seasonality_components',
        ),
        migrations.RemoveField(
            model_name='simulator',
            name='dataset',
        ),
    ]
