# Generated by Django 4.2.4 on 2023-09-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0008_rename_frequency_type_component_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dataconfigID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.dataconfig'),
        ),
    ]
