# Generated by Django 4.2.4 on 2023-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0009_alter_component_dataconfigid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10),
        ),
    ]
