# Generated by Django 4.2.4 on 2023-10-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0010_alter_component_dataconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='dataconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='simulator_api.dataconfig'),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='simulater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataConfig', to='simulator_api.simulator'),
        ),
    ]
