# Generated by Django 4.2.4 on 2023-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0011_alter_simulator_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='process_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
