# Generated by Django 4.2.4 on 2023-10-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0012_alter_simulator_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='metaData',
            field=models.CharField(default='', max_length=100),
        ),
    ]
