# Generated by Django 4.2.4 on 2023-09-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0012_alter_simulator_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulator',
            name='process_id',
        ),
    ]
