# Generated by Django 4.2.4 on 2023-10-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0013_alter_simulator_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulator',
            name='metaData',
        ),
    ]
