# Generated by Django 4.2.4 on 2023-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0015_simulator_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconfig',
            name='attribute_id',
            field=models.IntegerField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='dataconfig',
            name='generator_id',
            field=models.IntegerField(default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='simulator',
            name='producer_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
