# Generated by Django 4.2.4 on 2023-10-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0016_dataconfig_attribute_id_dataconfig_generator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='attribute_id',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dataconfig',
            name='generator_id',
            field=models.IntegerField(max_length=15),
        ),
    ]
