# Generated by Django 4.2.4 on 2023-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0018_alter_dataconfig_attribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='producer_type',
            field=models.CharField(choices=[('csv', 'csv'), ('xml', 'xsml'), ('sql', 'sql'), ('kafka', 'kafka')], max_length=25),
        ),
    ]
