# Generated by Django 4.2.4 on 2023-11-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0019_alter_simulator_producer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='airflow_daged',
            field=models.IntegerField(default=0),
        ),
    ]
