# Generated by Django 4.2.4 on 2023-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0021_dataconfig_seasonality_components_simulator_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconfig',
            name='missingPercent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
